[tox]
skipsdist = true
envlist = py311, py312, py313

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
passenv = PYTHON_VERSION
runner = uv-venv-lock-runner
dependency_groups = dev
commands =
    python -m pytest tests
    basedpyright whisper_subtitler tests
